### ISSUE TITLE
Possible to do OAuth logins without requiring mail.read

### ISSUE THREAD

**Issue by scottchiefbaker** [jasonjoh/php-tutorial#10]
I just went through your example and implemented it for our local Intranet. The login is working great, but I have a minor gripe. My Intranet login needs **only** needs the user's email address. To get this information I have to include the `mail.read` scope? When my users first click the link OAuth indicates it needs your logged in user credentials as well as the ability to *read your mail*. I'm not actually reading mail, and I'd rather not scare my users with that piece of info.

Is there a way, via OAuth, to get the users email address WITHOUT requiring `mail.read`?

**Comment by jasonjoh** [comment]
@scottchiefbaker the example uses the Mail API to get the user's email address via a get to `https://outlook.office.com/api/v2.0/Me`. In order to do that, you need some Outlook-related scope. The reason it does this is because it needs the email address associated with the user's Outlook account.

However, if you're just looking for identity and not accessing Outlook data, and you know for sure it's only users in your organization, you could extract the information from the identity token. It's likely the `preferred_username` claim has what you're looking for: https://azure.microsoft.com/en-us/documentation/articles/active-directory-token-and-claims/

**Comment by scottchiefbaker** [comment]
I'm a little bit of a n00b at this so bear with me. I'm getting an `id_token` back no problem, but I'm not sure what the next step should be to:
1. Validate that
2. Map that to an email address

In the example you posted here, it's using the `OutlookService::getUser()` function... I'd need something equivalent for an `id_token` right? Where do I send that `id_token` to get something usable back?

**Comment by jasonjoh** [comment]
It's a JSON Web Token (JWT). The full on specification for validating and parsing is spelled out in RFCs :). Azure has some guidance: https://azure.microsoft.com/en-us/documentation/articles/active-directory-v2-tokens/#validating-tokens

**Comment by scottchiefbaker** [comment]
Ya those RFCs are a little beyond me... That Azure documentation is pretty high level, and doesn't really help me with implementation details. I think it's a lost cause at this point.
